version: "3.7"
services:
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 127.0.0.1:4567:4567
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
